dist: trusty
sudo: false

language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
          apt:
            packages:
              - cmake
            sources:
              - kalakris-cmake

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
#
#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - cmake -H. -B build -DCMAKE_BUILD_TYPE=Release
  - cmake -B build

# after_success:
#   - mkdir coverage
#   - cd coverage
#   - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=yes ..
#   - make
#   - ctest
#   - lcov --directory . --capture --output-file coverage.info
#   - lcov --remove coverage.info '/usr/*' --output-file coverage.info
#   - lcov --remove coverage.info '*googletest*' --output-file coverage.info
#   - lcov --remove coverage.info '*.t.cpp' --output-file coverage.info
#   - lcov --list coverage.info
#   - bash <(curl -s https://codecov.io/bash) -f coverage.info
#   - cd ..
