dist: trusty
sudo: false

language: cpp

matrix:
  include:
    # - os: linux
    #   compiler: gcc
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test']
    #       packages: ['gcc-5', 'g++-5']
    #   env:
    #     - CC=gcc-5
    #     - CXX=g++-5

    # - os: linux
    #   dist: trusty
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources: ['llvm-toolchain-trusty-4.0']
    #       packages: ['clang-4.0']
    #   env:
    #     - CC=clang-4.0
    #     - CXX=clang++-4.0


    # - os: osx
    #   osx_image: xcode8
    #   compiler: gcc
    #   env:
    #     - CC=gcc
    #     - CXX=g++

    - os: osx
      osx_image: xcode8
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++



script:
  - cmake --version
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
  - cmake -Bbuild
  - cmake -Bbuild --target test

