dist: trusty
sudo: false

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILERCC=clang-4.0
        - COMPILERCXX=clang++-4.0


    - os: osx
      compiler: gcc
      env:
        - COMPILERCC=gcc
        - COMPILERCXX=g++

    - os: osx
      compiler: clang
      env:
        - COMPILERCC=clang
        - COMPILERCXX=clang++



script:
  - cmake --version
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
  - cmake -Bbuild

# after_success:
#   - mkdir coverage
#   - cd coverage
#   - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=yes ..
#   - make
#   - ctest
#   - lcov --directory . --capture --output-file coverage.info
#   - lcov --remove coverage.info '/usr/*' --output-file coverage.info
#   - lcov --remove coverage.info '*googletest*' --output-file coverage.info
#   - lcov --remove coverage.info '*.t.cpp' --output-file coverage.info
#   - lcov --list coverage.info
#   - bash <(curl -s https://codecov.io/bash) -f coverage.info
#   - cd ..